[package]
name = "rules_docker_compose_example"
version = "0.1.0"
edition = "2021"

[lib]
path = "rules_docker_compose_example.rs"

[dependencies]
reqwest = { version = "0.12", features = ["blocking"] }
